### Register a user
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "email": "jules.doe@javarush.dev",
    "password": "Jules@123"
}

### Login as a user
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "john.doe@javarush.dev",
    "password": "John@123"
}


### Get a list of all todos
GET http://localhost:8080/todos?page=1&size=4
Authorization: Bearer 4091d1ea-8166-447e-9cdb-2aa8cae62c76

### Create a todo
POST http://localhost:8080/todos
Content-Type: application/json
Authorization: Bearer 4091d1ea-8166-447e-9cdb-2aa8cae62c76

{
    "title": "Some todo title",
    "description": "Some todo description"
}


### Update a todo
PATCH http://localhost:8080/todos/57
Content-Type: application/json
Authorization: Bearer 4091d1ea-8166-447e-9cdb-2aa8cae62c76

{
    "title": "Buy groceries",
    "description": "Buy bread, butter, eggs, milk and fruits"
}


### Delete a todo
DELETE http://localhost:8080/todos/57
Authorization: Bearer 4091d1ea-8166-447e-9cdb-2aa8cae62c76
