### Create a new post

POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "content": "This is content",
  "category-id": 1,
  "tags": ["a", "b", "c", "d", "e"],
  "title": "Second article"
}

### Get all posts

GET http://localhost:8080/api/v1/posts

### Get post using id

GET http://localhost:8080/api/v1/posts/3

### Update Post

PATCH http://localhost:8080/api/v1/posts/2
Content-Type: application/json

{
  "title": "My first updaged post",
  "category-id": 2
}

### Delete post by id

DELETE http://localhost:8080/api/v1/posts/2